### ISSUE TITLE
add user doesn't work

### ISSUE THREAD

**Issue by dashtodartlang** [solus-project/budgie-desktop-branding#7]
Sorry ahead of time.  Not sure where this goes . . .
User -> add user doesn't work.  Tested in  Budgie and Gnome variants.

Issue:  Go to the user click add user section of Settings.  Unlock.  Add User.
Enter new user name.
- Alow user to set a password when they next login.  Next time you try to login, you have to type in a password, but there is not set password, and there is not option to set a new one.
- Set a password now:  does not work.  The Add button is still grayed out.

Should be allowed to either add user after setting password, or prompt to set password next time you try to login.

**Comment by ikeydoherty** [comment]
This is not a branding issue. If this is a Solus issue please report on https://dev.solus-project.com
